TARGET = :clang
ARCHS = armv7 arm64

BUNDLE_NAME = Reminders
Reminders_FILES = Reminders.m ListValue.m Add.m Overview.m Cell.m
Reminders_INSTALL_PATH = /Library/ProWidgets/Widgets/
Reminders_FRAMEWORKS = UIKit CoreGraphics QuartzCore EventKit
Reminders_LIBRARIES = prowidgets
Reminders_BUNDLE_EXTENSION = widget

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk