include @@THEOS@@/makefiles/common.mk

BUNDLE_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_INSTALL_PATH = /Library/ProWidgets/Themes/
@@PROJECTNAME@@_BUNDLE_EXTENSION = theme

include $(THEOS_MAKE_PATH)/bundle.mk