export TARGET = :clang
export ARCHS = armv7 arm64

BUNDLE_NAME = Blur
Blur_FILES = Blur.m
Blur_INSTALL_PATH = /Library/ProWidgets/Themes/
Blur_FRAMEWORKS = UIKit CoreGraphics QuartzCore
Blur_LIBRARIES = prowidgets
Blur_BUNDLE_EXTENSION = theme

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk